name: Build binaries

on: push

jobs:
  build-win:
    runs-on: windows-latest
    
    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Compile binary"
        run: |
          cmake -S . -B build
          cmake --build build --config Release

      - name: "List library files"
        run: |
          ls build/Release

      - name: "Upload binary"
        uses: actions/upload-artifact@v3
        with:
          name: Windows binary
          path: ${{ github.workspace }}\build\Release\rnnoise.dll
